load("fenrir.mac")$

/* Define the number of phases */
P : 2$

/* Define the states and inputs */
Y : [[x],[x]]$ declare(Y,scalar)$
U : [[v],[v]]$ declare(U,scalar)$
define_initial_and_final_states()$

/* Define initial and final times */
define_initial_and_final_times()$

/* Define the dynamics */
a : [[v],[v]]$

/* Define the objective */
eta : [xf1,0]$

/* Define phase interconnection constraints */
psi : [xf1-x02]$

/* Generate header files */
generate_headers()$
